### ISSUE TITLE
Dictionary naming conflict.

### ISSUE THREAD

**Issue by mark-cr** [Aplyca/ansible-role-mysql#1]
I believe there's a conflict with the `mysql` dictionary created in `defaults\main.yml` and the `mysql` dictionaries created in `vars\Debian.yml` and `vars\RedHat.yml`. By the time Ansible processes the condition on line 18 of `tasks\setup-Debian.yml`, the `mysql` dictionary has been redefined and no longer contains `mysql.install_server`.

When running the playbook in its current state, the following error occurs:

> TASK: [mauricios.MySQL | Ensure MySQL server is present using apt] ************
> fatal: [default] => error while evaluating conditional: mysql.install_server

I'm pretty new to Ansible, so please forgive me if I'm mistaken. Thanks for sharing!

**Comment by cocoy** [comment]
@mark-cr  I've encoutered the same problem, but I think on the ansible.cfg, you can set hash_behaviour=merge for the variables.

**Comment by mauricios** [comment]
@mark-cr thanks for trying this role and reporting issues and sorry for the late response.

As @cocoy  pointed out, this role uses `merge` hash behaviour to combine variables (like dictionaries in Python), so you should set this configuration by adding the setting `hash_behaviour=merge` to the `ansible.cfg` file which should be placed in the same directory where you are executing ansible-playbook command. 

See the docs for more info: http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour or see the example here: https://github.com/Aplyca/ansible-role-s3fs/blob/master/ansible.cfg
